### ISSUE TITLE
Grey screen - Nothing happens

### ISSUE THREAD

**Issue by jonatan-holmgren** [Merrit/feeling_finder#39]
I use the Linux version from the Arch Repos, but it won't load. It's just a grey screen.

Kind Regards, Jonte.

**Comment by Merrit** [comment]
Hi @Jontes-Tech :wave: 

Can you clarify or link to which package you are using?

The only packages I have created so far are portable and Flathub versions, and I don't see it in any Arch / AUR repository.

Did you try either of the [portable](https://github.com/Merrit/feeling_finder/releases/latest/download/FeelingFinder-Linux-Portable.tar.gz) or the [FlatHub](https://flathub.org/apps/details/codes.merritt.FeelingFinder) versions?

**Comment by jonatan-holmgren** [comment]
Oh, I am sorry. I meant the Flat hub version. Also happens with the Portable version

**Comment by Merrit** [comment]
Interesting. Which distro?

**Comment by jonatan-holmgren** [comment]
Arch Linux with Gnome, but many people on Flat hub have the same issue. I even have the same issue on the Portable one.

Kind Regards, Jonte.

**Comment by Merrit** [comment]
I've published version [0.5.1](https://github.com/Merrit/feeling_finder/releases/tag/v0.5.1), please give it a try. (Portable available now, Flathub version takes a little time to propagate.)

**Comment by jonatan-holmgren** [comment]
Will do!

**Comment by Merrit** [comment]
Is this still an issue?

**Comment by Merrit** [comment]
I'm going to close this as it appears to be resolved; if the issue persists please feel free to reopen it. :+1:
