### ISSUE TITLE
Flatpak version of App not Opening/Working in Void linux

### ISSUE THREAD

**Issue by ghost** [Merrit/feeling_finder#48]
I used the terminal to open the app and here is the output the terminal gives-

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: lock failed, path = '/home/ss/.var/app/codes.merritt.FeelingFinder/data/feeling_finder/storage/general.lock' (OS Error: Resource temporarily unavailable, errno = 11)
#0      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1002)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
<asynchronous suspension>
#4      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
<asynchronous suspension>
#5      StorageService.init (package:feeling_finder/src/storage/storage_service.dart:36)
<asynchronous suspension>
#6      main (package:feeling_finder/main.dart:24)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: FileSystemException: lock failed, path = '/home/ss/.var/app/codes.merritt.FeelingFinder/data/feeling_finder/storage/general.lock' (OS Error: Resource temporarily unavailable, errno = 11)
#0      _RandomAccessFile.lock.<anonymous closure> (dart:io/file_impl.dart:1002)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      StorageBackendVm.initialize (package:hive/src/backend/vm/storage_backend_vm.dart:81)
<asynchronous suspension>
#3      HiveImpl._openBox (package:hive/src/hive_impl.dart:116)
<asynchronous suspension>
#4      HiveImpl.openBox (package:hive/src/hive_impl.dart:145)
<asynchronous suspension>
#5      StorageService.init (package:feeling_finder/src/storage/storage_service.dart:36)
<asynchronous suspension>
#6      main (package:feeling_finder/main.dart:24)
<asynchronous suspension>

**Comment by Merrit** [comment]
Hi @CapeCrusader321 :wave: 

Thanks for opening the issue!

I think this is because there is an instance already running on your system. You can try to kill it from the system monitor, or from terminal:

```bash
killall feeling_finder
```
or even by rebooting.

I will also look into a check at startup, and if there is an instance already running the app can kill it so it can proceed.

**Comment by ghost** [comment]
> Hi @Merrit  thanks for checking out, but sadly none of your suggestion seems to work..

**Comment by Merrit** [comment]
Really, even after rebooting the computer it still won't open? With the same error? :thinking:

**Comment by ghost** [comment]
@Merrit Yes i have done multiple reboot yet no results

**Comment by raluvy95** [comment]
Same issue, here's an error trying to run the app after `killall feeling_finder`
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: No element
#0      _GrowableList.last (dart:core-patch/growable_array.dart:348)
#1      Flatpak._systemThemeMode (package:flutter_flatpak/flutter_flatpak.dart:31)
<asynchronous suspension>
#2      Flatpak.init (package:flutter_flatpak/flutter_flatpak.dart:20)
<asynchronous suspension>
#3      SettingsService.themeMode (package:feeling_finder/src/settings/settings_service.dart:78)
<asynchronous suspension>
#4      SettingsCubit.init (package:feeling_finder/src/settings/cubit/settings_cubit.dart:33)
<asynchronous suspension>
#5      main (package:feeling_finder/main.dart:31)
<asynchronous suspension>
```

**Comment by ghost** [comment]
This Probably means its a bug which need to be fixed, i am sure you will work on it....

**Comment by Merrit** [comment]
Have been without power for a few days following bad weather here. I will look into this soon as I can :)

**Comment by Merrit** [comment]
v0.8.0 is being published to Flathub shortly, hopefully will fix the issue(s) you've encountered; please update when available and let me know :)

**Comment by ghost** [comment]
ok
