### ISSUE TITLE
Wrong version of emojies.

### ISSUE THREAD

**Issue by Atlaimond** [Merrit/feeling_finder#56]
System: **Linux Mint 21.1**
Program: **Thunderbird 102.11.0 (64-bit)**

Hello.
The [WARNING] and the [SUN] _(there could be more 🤷‍♂️)_ emojis paste a line-art version of that emoji instead of the coloured version.
It wasn't an issue in the previous version of **Feeling Finder**. 

### Thunderbird:
![Screenshot_2023-05-26_12-56-36](https://github.com/Merrit/feeling_finder/assets/75715297/2179e609-52f6-4fc9-bd17-ad151e3cec73)

emojipedia.org :
⚠️
☀️
Feeling Finder:
⚠
☀

### In the editor here, it also visible the difference:
![Screenshot 2023-05-26 at 13-00-46 New Issue · Merrit_feeling_finder](https://github.com/Merrit/feeling_finder/assets/75715297/9b256070-0ade-476d-8849-246de1a72561)

I have no idea what causes this. I hope you do. 🙏😟
Best regards, Atlaimond

**Comment by Merrit** [comment]
Hey @Atlaimond :wave: Thanks for opening the issue!

I can confirm the problem here. Seems the new source of emojis has some that are the lineart version for some reason. If it is only these two emoji that are an issue for you, I can add a quick patch for them for you; otherwise will have to give some thought on how to automate pulling in the emoji set from the Unicode database directly instead of relying on a 3rd party package.

**Comment by Atlaimond** [comment]
Thank you. I'm testing your **[Feeling Finder]** now.
I've just done with the "Smileys & Emotion" category. 
Here is the list which of them paste the line-art version:

`Smiling Face`
`Frowning Face`
`Skull and Crossbones`
`Index Pointing Up`
`Writing Hand`
`Umbrella`

I'll continue the testing as soon as my fingers rested a bit. 🙂👍 _ 🤌💤

![Smileys   Emotion - May 27th 2023](https://github.com/Merrit/feeling_finder/assets/75715297/7060944a-8d86-46e3-9982-1f2a7582f15a)

**Comment by Merrit** [comment]
You might be able to look [here](https://raw.githubusercontent.com/Fintasys/emoji_picker_flutter/59bc8693f91b1512c4c9d5b102a4c1bdc6fe6dfe/lib/src/default_emoji_set.dart) to quickly see which emojis are the lineart versions.

I've been experimenting with getting a better set of emojis, but they are more complicated than they have a right to be. :sweat_smile:

**Comment by Atlaimond** [comment]
Thank you. I will look into it. 
Since I've done with some other categories in the manual way, I post here them. At least it can be as a confirmation that it really pastes incorrectly. 

``
``
``

**Comment by Atlaimond** [comment]
Thank you. I will look into it. 
Since I've done with some other categories in the manual way, I post here them. At least it can be as a confirmation that it really pastes incorrectly. 

**___ Animals and Nature ___**
`Shamrock`
`Sun`
`Cloud`
`Umbrella`
`Snowflake`
`Snowman`
`Comet`
_____________
**___ Food and Drink ___**
_____________
**___ Travel & Places ___**
 `Airplane`
_____________
**___ Activities ___**
`Chess Pawn`
_____________
![Animals and Nature](https://github.com/Merrit/feeling_finder/assets/75715297/f06f0647-082a-46b4-ad86-810ad46fb9ad)
![Food and Drink](https://github.com/Merrit/feeling_finder/assets/75715297/191b2f39-221e-4877-a2a4-be15c4920b2a)
![Travel   Places](https://github.com/Merrit/feeling_finder/assets/75715297/76e698cb-f614-425f-b1d6-de2e2cc0d355)
![Animals and Nature](https://github.com/Merrit/feeling_finder/assets/75715297/b8e6a8f1-abda-4686-bf5c-62caf3d64738)

**Comment by Atlaimond** [comment]
> You might be able to look [here](https://raw.githubusercontent.com/Fintasys/emoji_picker_flutter/59bc8693f91b1512c4c9d5b102a4c1bdc6fe6dfe/lib/src/default_emoji_set.dart) to quickly see which emojis are the lineart versions.

Cool. Let me know if you want me to continue this testing, or just check through the website you linked here. 👍

**Comment by Merrit** [comment]
I think we are good with what we have for now. Thanks for your diligent investigation, it is much appreciated! :heart:

**Comment by Atlaimond** [comment]
Okay. Cool! ✌️😎
Then here is the remaining categories, and this time I've checked them in **Firefox** 113.0.2 (64-bit) for Linux Mint mint-001 - 1.0, the website you linked here.

**___ Category.OBJECTS ___**
`Telephone`
`Envelope`
`Scissors`
`Hammer and Pick`
`Black Nib`
`Crossed Swords`
`Gear`
`Balance Scale`
`Alembic`
`Coffin`
`Funeral Urn`
**___ Category.SYMBOLS ___**
`Heavy Heart Exclamation`
`Red Heart`
`Hot Springs`
`Spade Suit`
`Heart Suit`
`Diamond Suit`
`Club Suit`
`Warning`
`Radioactive`
`Biohazard`
`Up Arrow`
`Up-Right Arrow`
`Right Arrow`
`Down-Right Arro`
`Down Arrow`
`Down-Left Arrow`
`Left Arrow`
`Up-Left Arrow`
`Up-Down Arrow`
`Left-Right Arrow`
`Right Arrow Curving Left`
`Left Arrow Curving Right`
`Right Arrow Curving Up`
`Right Arrow Curving Down`
`Right Arrow Curving Down`
`Star of David`
`Wheel of Dharma`
`Yin Yang`
`Latin Cross`
`Orthodox Cross`
`Star and Crescent`
`Peace Symbol`
`Play Button`
`Reverse Button`
`Eject Button`
`Infinity`
`Ballot Box With Check`
`Heavy Check Mark`
`Part Alternation Mark`
`Eight-Spoked Asterisk`
`Eight-Pointed Star`
`Sparkle`
`Double Exclamation Mark`
`Exclamation Question Mark`
`Copyright`
`Registered`
`Trade Mark`
`A Button (Blood Type)`
`B Button (Blood Type)`
`Information`
`Circled M`
`O Button (Blood Type)`
`P Button`
`Japanese “Service Charge” Button`
`Japanese “Monthly Amount” Button`
`Japanese “Congratulations” Button`
`Japanese “Secret” Button`
`White Medium Square`
`White Small Square`
**___ Category.FLAGS ___**
All good. 👍

**Comment by Merrit** [comment]
I've created a package that generates up to date emojis, and so far seems to be working well. Perhaps you'd like to give it a try and see if it is working for you?

[FeelingFinder-Linux-Portable.tar.gz](https://github.com/Merrit/feeling_finder/files/11602496/FeelingFinder-Linux-Portable.tar.gz)

[FeelingFinder-Windows-Portable.zip](https://github.com/Merrit/feeling_finder/files/11602497/FeelingFinder-Windows-Portable.zip)

**Comment by Atlaimond** [comment]
Done!
They seem too work properly! 



![Screenshot_2023-05-31_06-23-57](https://github.com/Merrit/feeling_finder/assets/75715297/bd89a8e0-c153-4053-a43b-cb0f190c74a5)

I couldn't find these 
![Screenshot_2023-05-31_06-20-56](https://github.com/Merrit/feeling_finder/assets/75715297/7ead2a3a-0756-4a97-83ba-2617e4dfc7fa)

This heart is red, and not black.
![Screenshot_2023-05-30_20-14-30](https://github.com/Merrit/feeling_finder/assets/75715297/22770f9f-2878-4906-b0f5-a18c69eff6a0)
![Screenshot_2023-05-30_20-12-46](https://github.com/Merrit/feeling_finder/assets/75715297/f03f3065-41bb-461e-a2c4-d4a2801376e8)
![Screenshot_2023-05-30_20-12-32](https://github.com/Merrit/feeling_finder/assets/75715297/9ff8cd79-b605-46fb-9c4b-5f873c6fd862)
![Screenshot_2023-05-30_20-12-17](https://github.com/Merrit/feeling_finder/assets/75715297/5dc3be61-9025-4a80-b885-413af84ea89f)
![Screenshot_2023-05-30_20-12-09](https://github.com/Merrit/feeling_finder/assets/75715297/93837dac-10b3-441d-acfd-806ee9c8822b)


Index Finfer up tag issue.
![Screenshot_2023-05-30_20-13-39](https://github.com/Merrit/feeling_finder/assets/75715297/cb28c665-f18f-44fc-8f11-5729450a5bf9)
![Screenshot_2023-05-30_20-04-54](https://github.com/Merrit/feeling_finder/assets/75715297/e58bc3e2-a347-41dc-9236-e98a187f6e89)

Sorry for the mess. I'm running out of time so I had to hurry. 
I hope it helps!

**Comment by Merrit** [comment]
> Japanese “Service Charge” Button was approved as part of [Unicode 6.0](https://emojipedia.org/unicode-6.0/) in 2010 under the name “Squared Katakana Sa” and added to [Emoji 1.0](https://emojipedia.org/emoji-1.0/) in 2015. [^1]

This dataset seems to have it under "Squared Katakana Sa".

> Note: the Unicode Character Database (UCD) name “Black Heart Suit” pre-dates color emoji, when the term referred to a solid, [black](https://emojipedia.org/glossary/#black) ♥ heart suit character. See the glossary for information on the term black in Unicode character names. [^2]

> When describing pre-emoji Unicode symbols, black in a character names refers to the symbol being solid/filled in.
> 
> Example: [☀️ Sun](https://emojipedia.org/sun/) has the Unicode Character Database name of "Black Sun With Rays", but this does not refer to the ethnicity of the character. This means that when shown with monochrome fonts, this character is intended to be displayed with a solid or filled-in appearance. [^3]

Seems to be a quirk of emoji history, and surprisingly it is correct. :smile: 

Index finger is [here](https://github.com/Merrit/unicode_emojis/blob/65ef8e17b48392e5c2a85f194cfaa062d180ef04/lib/src/emoji_dataset.dart#L7408), under the name "white up pointing index". Looking at this lead me to find that the search only works currently in the same order the term appears, so for example "pointing index" finds this, but "index pointing" does not - I will look at changing the search algorithm to allow this! :grin: 

Thanks for testing, very helpful! 💙

[^1]: https://emojipedia.org/japanese-service-charge-button/
[^2]: https://emojipedia.org/heart-suit/
[^3]: https://emojipedia.org/glossary/#black

**Comment by Merrit** [comment]
Updated build with new search algorithm:

[FeelingFinder-Linux-Portable.tar.gz](https://github.com/Merrit/feeling_finder/files/11616933/FeelingFinder-Linux-Portable.tar.gz)

[FeelingFinder-Windows-Portable.zip](https://github.com/Merrit/feeling_finder/files/11616941/FeelingFinder-Windows-Portable.zip)

**Comment by Atlaimond** [comment]
It feels lovely to be of remembering correct word order with "finger up". ❤️ Thanks! 🙇‍♂️⭐

About the hears' colours:
I understand now the reason behind this missing "red heart". Unfortunately, it still feels uncomfortable, and even un-logical, since there are yellow, green, blue, etc. -hears, I mean 9 pieces differently coloured hears right there, and only the red-heat cannot be extracted as "red heart".

It's just weird. But, I think I may be able to get used to it. Since everything else work well in [Feeling Finder]. 🤗💛

About the Japanese emojis, I have never used those, and I think I'll never be. So, I'm fine as they work currently. 😊👌

Thank you again for your hard work. I'll buy you some coffee for it. 💳😉☕
Have a good day, @Merrit . 👋🙂

PS. I used your latest [Feeling Finder], you sent, for these emojis to put here. 😉👌

**Comment by Merrit** [comment]
I agree, it is weird! I went ahead and added a tweak to our search algorithm, so it will include red hearts now like expected!

![image](https://github.com/Merrit/feeling_finder/assets/9575627/c36d6d21-537c-4fe0-9a84-4521e6d805e1)

Also, thank you so much for the support - it really means a lot to me! 🎉🎉🎉🎉🎉 💪 🙇‍♀️

**Comment by Atlaimond** [comment]
Thank you for the extra-extra work on the search algorithm. 🤗 
Now, no one have to get used the weirdness, thanks to you! 🙌😊🎆
