### ISSUE TITLE
Started Building and Maintaining Snap Packages

### ISSUE THREAD

**Issue by ghost** [Merrit/feeling_finder#58]
Hey there i have started building and maintaining a snap package for this app.

Manifest.Source: https://github.com/CapeCrusader321/feeling_finder-snap

<a href="https://snapcraft.io/feeling-finder">
  <img alt="Get it from the Snap Store" src="https://snapcraft.io/static/images/badges/en/snap-store-black.svg" />
</a>

**Comment by Merrit** [comment]
That's awesome, nice job! :tada: :grinning: 

Would you like to add the link to the README?

**Comment by ghost** [comment]
> That's awesome, nice job! tada grinning
> 
> Would you like to add the link to the README?

Sure i would love the snap package to be another alternate method to distribute the app
