### ISSUE TITLE
Update on the snap packages.

### ISSUE THREAD

**Issue by ghost** [Merrit/feeling_finder#75]
Hey there @Merrit this is a friendly update for you, i have shifted the snap builds/manifest to launchpad from github for my personal convenience. This helps me streamline my efforts to package this app as a snap.
Also the newer snap versions have been refactored and made more aligned with the upstream (using upstream provided desktop file and metainfo file) etc.
Thanks.

**Source:**  https://code.launchpad.net/~capecrusader-121/miscellaneous-snaps/+git/feeling_finder-snap
**For snap specific issues:**  https://bugs.launchpad.net/miscellaneous-snaps

**Comment by Merrit** [comment]
Very nice! Thanks for the update :grinning: 

Do you happen to know if that means [this](https://github.com/Merrit/feeling_finder/issues/67) issue is resolved then?

**Comment by ghost** [comment]
> Very nice! Thanks for the update grinning
> 
> Do you happen to know if that means [this](https://github.com/Merrit/feeling_finder/issues/67) issue is resolved then?

Ya, we can consider it done.

**Comment by Merrit** [comment]
Excellent, thanks again!

💙 :tada: ˗ˏˋ ★ˎˊ˗
