### ISSUE TITLE
Option to disable panel icon/ system tray icon

### ISSUE THREAD

**Issue by ghost** [Merrit/feeling_finder#79]
Self-explanatory on non-gtk DEs like lxqt the sys-tray icon looks ugly due to non-integration of gtk libs into such DEs, as such there should be a option to disable if the user wishes.

**Comment by Merrit** [comment]
Thanks for the suggestion!

Added in [v1.3.0](https://github.com/Merrit/feeling_finder/releases/tag/v1.3.0). :+1: :rainbow:

**Comment by ghost** [comment]
Thanks.
