### ISSUE TITLE
Tray Icon doesn't Work

### ISSUE THREAD

**Issue by sameersharma2006** [Merrit/feeling_finder#87]
Snap maintainer here, the tray icon doesn't work in Gtk DEs Like Gnome & Xfce although works fine in Lxqt !

See for more details ->  https://bugs.launchpad.net/sundry/+bug/2040454

P.S. I have staged the needed lib. -> https://github.com/sameersharma2006/feeling-finder/blob/1be8af08d2f1325efea4d02e4fa87728d93ad42c/snapcraft.yaml#L51

**Comment by Merrit** [comment]
Interesting, seems like it may be a Wayland issue.

The base portable build works fine, but the Flatpak also has this issue. If I remove the Flatpak permission for Wayland so it reverts to x11, the tray icon works.

**Comment by sameersharma2006** [comment]
Hmm, I will try removing the Wayland plug for the snap,  but AFAIK Xubuntu runs on x11.

**Comment by sameersharma2006** [comment]
```
(feeling_finder:4183): Gtk-CRITICAL **: 08:05:48.072: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

_**After i disabled wayland i get the following bash output ;**_

```
(feeling_finder:3745): Gtk-WARNING **: 09:29:10.326: GTK+ module /snap/feeling-finder/52/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 09:29:10.326: Failed to load module "canberra-gtk-module"

```

**Comment by Merrit** [comment]
`libcanberra` seems to be for playing sounds, which this app doesn't do.

Also says it detects GTK 2 libs, so maybe that is causing an issue..

-----

I discovered that in Flatpak the icon has to be passed as the name, rather than the path - since the sandbox and host see different paths. Which I sort of got working, but now mysteriously doesn't so I am trying to troubleshoot further.

**Comment by Merrit** [comment]
I got the tray icon working in Flatpak Wayland, and also added logic to check for if it is running in Snap.

Here is the updated build if you'd like to test it:

~~[FeelingFinder-Linux-Portable.tar.gz](https://github.com/Merrit/feeling_finder/files/14736410/FeelingFinder-Linux-Portable.tar.gz)~~

If run from CLI with the `-v` flag it will output the name it is using for the icon to the log, which when sandboxed should be `codes.merritt.FeelingFinder`.

-----

Now I think about it, there may need to be another change to support Snap..

**Comment by Merrit** [comment]
This build should hopefully cover everything for Snap:

[FeelingFinder-Linux-Portable.tar.gz](https://github.com/Merrit/feeling_finder/files/14736521/FeelingFinder-Linux-Portable.tar.gz)

**Comment by sameersharma2006** [comment]
I will test out the provided build, thanks.

**Comment by sameersharma2006** [comment]
Hey there no fix yet !

Without -v flag.

```
Gtk-Message: 09:27:22.969: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(feeling_finder:5863): Gtk-WARNING **: 09:27:23.057: GTK+ module /snap/feeling-finder/53/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 09:27:23.057: Failed to load module "canberra-gtk-module"

(feeling_finder:5863): Gtk-WARNING **: 09:27:23.060: GTK+ module /snap/feeling-finder/53/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 09:27:23.060: Failed to load module "canberra-gtk-module"

** (feeling_finder:5863): CRITICAL **: 09:27:23.151: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (feeling_finder:5863): CRITICAL **: 09:27:23.154: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

(feeling_finder:5863): libappindicator-CRITICAL **: 09:27:23.236: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed
```

With -v flag, the cli messages are 
```
Gtk-Message: 09:29:04.250: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(feeling_finder:6064): Gtk-WARNING **: 09:29:04.328: GTK+ module /snap/feeling-finder/53/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 09:29:04.328: Failed to load module "canberra-gtk-module"

(feeling_finder:6064): Gtk-WARNING **: 09:29:04.329: GTK+ module /snap/feeling-finder/53/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 09:29:04.329: Failed to load module "canberra-gtk-module"

** (feeling_finder:6064): CRITICAL **: 09:29:04.406: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found

** (feeling_finder:6064): CRITICAL **: 09:29:04.409: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
flutter:   TRACE ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   TRACE │ #0   LoggingManager.initialize (package:feeling_finder/src/logs/logging_manager.dart:49)
flutter:   TRACE │ #1   <asynchronous suspension>
flutter:   TRACE ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   TRACE │  Logger initialized.
flutter:   TRACE └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

(feeling_finder:6064): libappindicator-CRITICAL **: 09:29:04.462: app_indicator_set_menu: assertion 'IS_APP_INDICATOR (self)' failed
flutter:   TRACE ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter:   TRACE │ #0   SystemTray.show (package:feeling_finder/src/system_tray/system_tray.dart:48)
flutter:   TRACE │ #1   new SettingsCubit._ (package:feeling_finder/src/settings/cubit/settings_cubit.dart:35)
flutter:   TRACE ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter:   TRACE │  Setting system tray icon to codes.merritt.FeelingFinder
flutter:   TRACE └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

**Comment by sameersharma2006** [comment]
Just a suggestion...

I think a better approach would be to drop tray-icon support, tray-icon isn't supported by GTK 4+ , P.S. Gnome dropped support for it long back AFAIK with Gnome 3.26 .

-> https://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray


This will also allow room for new features and reduce maintenance efforts.

**Comment by Merrit** [comment]
```
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
```

This line is still showing GTK 2 conflicts, which may or may not be related.

```
** (feeling_finder:5863): CRITICAL **: 09:27:23.151: Failed to read XDG desktop portal settings: GDBus.Error:org.freedesktop.portal.Error.NotFound: Requested setting not found
```

Does the Snap manifest need to specify dbus interfaces? The Flatpak needs `--talk-name=org.kde.StatusNotifierWatcher` as specified in the [docs for tray icons](https://docs.flatpak.org/de/latest/desktop-integration.html#status-icons).

> drop tray-icon support

Personally I use tray icons for several apps, and I think GNOME attempting to drop the concept is a mistake. That said, it works even though the tray icon doesn't load so if you'd rather not support that for the Snap its fine with me.

**Comment by Merrit** [comment]
I merged the fix so I could get a release out with it, since it resolves the issue for Flatpak.

If it still isn't working after investigating the gtk and dbus permissions for Snap, feel free to reopen.

**Comment by Recydywa** [comment]
Snap has dbus interface.

https://forum.snapcraft.io/t/the-dbus-interface/2038

The Feeling Finder doesn't have that interface specified at all, but I do have several snaps installed with dbus interface. 

In fact among them are both Firefox, and Thunderbird use dbus interface.

**Comment by Merrit** [comment]
I'm not very familiar with Snap configurations, I gave up on them partly because of the terrible support. I'd recommend you check the policy with them.

**Comment by sameersharma2006** [comment]
@Merrit  What's the DBUS-ID for feeling-finder ?

As a simple emoji-picker tool i didn't thought it would need DBUS at all .

**Comment by Merrit** [comment]
As I said a bit further up, the system tray library seems to use the `org.kde.StatusNotifierWatcher` dbus interface, which is why I had to [give the Flatpak access to that](https://github.com/flathub/codes.merritt.FeelingFinder/blob/ce3756f88ab6d77b6eabfdffe5c11714f05c5601/codes.merritt.FeelingFinder.yml#L19).

I don't think it should require anything specific beyond that.

**Comment by sameersharma2006** [comment]
@Merrit  If so AFAIK it won't be necessary to add DBUS & Also consider the fact that tray icon works fine in Non-Gtk DEs like Lxqt as i said before, so its not something wrong with the snap.

P.S. @Recydywa  Can you check if the issue persists with the latest snap version(1.4.3) , if possible ?

**Comment by Recydywa** [comment]
I'm using Unity as my DE and with the latest version of snap package I do see the tray icon.

And every action that the tray icon provides works.

**Comment by sameersharma2006** [comment]
@Recydywa  Thanks for confirming, so i think this concludes its working fine in snap although will still need someone to check if Ubuntu Gnome,Xfce and Mate are fine.

If this issue persists in such DEs than its an issue with the DEs not the snap.

_***DEs= Desktop Environments.**_

**Comment by Merrit** [comment]
> Also consider the fact that tray icon works fine in Non-Gtk DEs like Lxqt

Actually I confirmed the issue was affecting Flatpak + KDE, so it wasn't alright on Qt based desktops entirely. The update to the app & giving the Flatpak access to that dbus interface are what confirmed the fix for KDE.

**Comment by sameersharma2006** [comment]
@Merrit  Hmm, Can't say for KDE but Lxqt always worked fine from the beginning( since i created the snap package).
