### ISSUE TITLE
Flatpak runtime requires update

### ISSUE THREAD

**Issue by Atlaimond** [Merrit/feeling_finder#93]
Looking for updates…
Info: org.gnome.Platform//44 is end-of-life, with reason:
   The GNOME 44 runtime is no longer supported as of March 20, 2024. Please ask your application developer to migrate to a supported platform.
Applications using this runtime:
   codes.merritt.FeelingFinder
Nothing to do.

It works still cool, though. 🙂👍

**Comment by Merrit** [comment]
Thanks for letting me know! I will look into upgrading that shortly. :grin:

**Comment by Merrit** [comment]
Thanks again for reporting this, should be good now. :+1:
