### ISSUE TITLE
[Feature Request] Discoverability of keyboard shortcuts

### ISSUE THREAD

**Issue by Merrit** [Merrit/feeling_finder#99]
There is nothing in-app to indicate what shortcuts are available. There should be an easy way for a user to discover them, or remind themselves of what they are.

- [X] Document in README dbeeb338e4b6e8f624e644e1dffc7eacf4078bc6
- [x] Add in-app discoverability

**Comment by gpunktschmitz** [comment]
maybe also adding it to the readme of the repository (this is also where the app points to)

**Comment by Merrit** [comment]
Absolutely :100:
